version: "1"
services:
  my-info-app:
    # container_name: spring-app
    image: my-info-app
    restart: always
    build: .
    ports:
      - 9000-9010:9090
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: angad@db
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: my-info
      MYSQL_ROOT_PASSWORD: angad@db

